name: RDP-HighPerf

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    timeout-minutes: 3600

    steps:
      - name: Enable RDP and Optimize System
        run: |
          # เปิด RDP
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0 -Force
          
          # ปิด services ที่ไม่จำเป็น เพื่อรีด CPU/RAM
          Stop-Service -Name "wuauserv" -Force   # Windows Update
          Stop-Service -Name "SysMain" -Force    # Superfetch
          Stop-Service -Name "DiagTrack" -Force  # Telemetry
          
          # ปิด sleep/hibernation
          powercfg -h off

      - name: Create High-Privilege RDP User
        run: |
          $password = "Rdp$((New-Guid).Guid.Substring(0,8))!"
          $sec = ConvertTo-SecureString $password -AsPlainText -Force
          New-LocalUser "RDPUser" -Password $sec -AccountNeverExpires
          Add-LocalGroupMember -Group "Administrators" -Member "RDPUser"
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member "RDPUser"
          echo "RDP_PASSWORD=$password" >> $env:GITHUB_ENV

      - name: Install Tailscale
        run: |
          $url = "https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi"
          $out = "$env:TEMP\tailscale.msi"
          Invoke-WebRequest $url -OutFile $out
          Start-Process msiexec.exe -ArgumentList "/i $out /quiet /norestart" -Wait

      - name: Connect Tailscale
        run: |
          & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-rdp-${{ github.run_id }}
          $tsip = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4
          echo "TAILSCALE_IP=$tsip" >> $env:GITHUB_ENV

      - name: Show RDP Credentials
        run: |
          echo "============================="
          echo "   Tailscale RDP Connected   "
          echo "============================="
          echo "IP Address: $env:TAILSCALE_IP"
          echo "Username:   RDPUser"
          echo "Password:   $env:RDP_PASSWORD"
          echo "============================="

      - name: Keep Session Alive
        run: |
          while ($true) {
            Write-Host "[$(Get-Date)] RDP session active"
            Start-Sleep -Seconds 300
          }
