name: RDP-Tailscale

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Enable RDP
        run: |
          # เปิด Remote Desktop
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0 -Force
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Restart-Service -Name TermService -Force

      - name: Create RDP User
        run: |
          $username = "RDP"
          $password = "RDP"
          $sec = ConvertTo-SecureString $password -AsPlainText -Force
          if (-not (Get-LocalUser -Name $username -ErrorAction SilentlyContinue)) {
              New-LocalUser $username -Password $sec -AccountNeverExpires
          }
          Add-LocalGroupMember -Group "Administrators" -Member $username
          Add-LocalGroupMember -Group "Remote Desktop Users" -Member $username
          echo "RDP_USERNAME=$username" >> $env:GITHUB_ENV
          echo "RDP_PASSWORD=$password" >> $env:GITHUB_ENV

      - name: Install Tailscale
        run: |
          Invoke-WebRequest https://pkgs.tailscale.com/stable/tailscale-setup-latest-amd64.msi -OutFile tailscale.msi
          Start-Process msiexec.exe -ArgumentList '/i tailscale.msi /qn' -Wait
          setx PATH "$env:ProgramFiles\Tailscale;$env:PATH"

      - name: Start Tailscale
        run: |
          # Auth ผ่าน Ephemeral key (สร้างจาก admin.tailscale.com → Keys)
          tailscale up --authkey ${{ secrets.TAILSCALE_AUTHKEY }} --hostname github-rdp --accept-routes
          tailscale ip -4 | Out-File ip.txt
          Get-Content ip.txt

      - name: Show Info
        run: |
          $ip = Get-Content ip.txt
          echo "============================="
          echo "   RDP via Tailscale Ready   "
          echo "============================="
          echo "Connect to: $ip"
          echo "Username:   $env:RDP_USERNAME"
          echo "Password:   $env:RDP_PASSWORD"
          echo "============================="

      - name: Keep Alive
        run: |
          while ($true) {
            Write-Host "[$(Get-Date)] RDP session active"
            Start-Sleep -Seconds 300
          }
